### ISSUE TITLE
what's the parameter 'leaf width' mean

### ISSUE THREAD

**Issue by superFilicos** [pbelcak/fastfeedforward#7]
Hi ！
       May I ask what's the parameter 'leaf width' mean? Looking forward for your reply!

**Comment by pbelcak** [comment]
Hi,

In the original [August pre-print](https://arxiv.org/abs/2308.14711) we trained FFFs that could have multiple neurons as leaves of the FFF trees (rather than the leaves being just single-neuron nodes just like their parents). There, the `leaf_width` is just the width (i.e. the hidden width) of each leaf network of the tree.

This has proven to be less efficient than having all leaves have a single node, and so we dropped it when working towards UltraFastBERT.
